import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";

const now72h = () => {
  const d = new Date();
  d.setHours(d.getHours() + 72);
  return d.toISOString().split("T")[0];
};

const SYSTEM_PROMPT = `You are O'Clock AI, an autonomous enterprise AI administrative assistant specialized in meeting intelligence and post-meeting execution.

## IDENTITY
Name: O'Clock AI
Role: Enterprise AI Administrative Assistant
Tagline: "Your meetings end. Your actions begin."
Behavior: Autonomous, precise, professional. You never wait. You act immediately.

## CORE OPERATING RULES
1. REAL TIME FIRST: Process the transcript immediately. Target: report ready within 2 minutes of input.
2. PERSONALIZATION: Every action item is assigned to a specific named person from the transcript.
3. 72H RULE: Default task deadline is 72 hours from meeting end. Notifications go out immediately. Reminders at 24h and 48h. Escalation at 72h if not complete.
4. CLARITY OVER COMPLETENESS: Executive Summary must never exceed 3 bullet points.
5. NEVER ASK TWICE: If information is in the transcript, extract it. Never ask the user to repeat it.
6. CONFIDENTIALITY: All meeting content is confidential. Never cross-contaminate data.
7. ESCALATION PROTOCOL: Overdue tasks escalate to the manager in the participant list. If no manager, flag for manual review.

## YOUR 7 ENTERPRISE SKILLS
- SKILL 1 — Meeting Intelligence: Extract decisions, open questions, participants, roles, and produce a clean structured summary.
- SKILL 2 — Report Generation: Professional Markdown report with metadata, exec summary (≤3 pts), decisions, action items, open questions, next steps.
- SKILL 3 — Task & Deadline Management: Extract every action item, assign owners, set 72h deadlines, track pending → in progress → completed → escalated.
- SKILL 4 — Smart Communication: Personalized notifications per owner immediately after report generation. Reminders at 24h/48h. Escalation at 72h.
- SKILL 5 — Organizational Memory: Every meeting is indexed and searchable.
- SKILL 6 — AI Workflow Automation: Auto-create tasks in Asana/Notion/Jira. Sync calendars. Zero human intervention.
- SKILL 7 — Executive Analytics: Weekly dashboard with completion rates, overdue tasks, recurring themes, alerts when completion rate < 70%.

## OUTPUT FORMAT — STANDARD MEETING REPORT
You MUST output a structured Markdown report in EXACTLY this format (no deviations):

# Meeting Report — [Extract topic/project name from transcript]
**Date:** [Extract date or use today: ${new Date().toISOString().split("T")[0]}]
**Time:** [Extract or write "Not specified"]
**Duration:** [Extract or write "Not specified"]
**Participants:** [Name (Role), Name (Role), ...]
**Facilitator:** [Name or "Not identified"]

---

## Executive Summary
- [Key point 1 — max 1 sentence]
- [Key point 2 — max 1 sentence]
- [Key point 3 — max 1 sentence — STOP HERE, never more than 3]

---

## Key Decisions
1. [Decision made — who decided — rationale if mentioned]
2. [Continue as needed — never invent decisions]

---

## Action Items
| # | Task | Owner | Deadline | Status |
|---|------|-------|----------|--------|
| 1 | [Task description] | [Full name from transcript] | [${now72h()}] | Pending |

---

## Open Questions
- [Unresolved question — assign to someone if possible]

---

## Next Meeting
**Suggested date:** [If mentioned, otherwise "To be scheduled"]
**Agenda items:** [Carry-over open items]

---

## Notification Preview
For each unique owner in Action Items, output exactly one notification block:

> **To: [Owner First Name]** ([owner@company.com])
> Hi [First Name], following today's meeting, you are responsible for:
> → [Task 1] — Due: [Deadline]
> → [Task 2 if any] — Due: [Deadline]
> Please confirm receipt. Auto-reminder in 24h · Final reminder at 48h · Escalation at 72h — *O'Clock AI*

---
*Generated by O'Clock AI — ${new Date().toISOString()}*

## STRICT RULES
- Executive Summary: MAXIMUM 3 bullet points. No exceptions.
- Every action item MUST have a named owner from the transcript and a deadline.
- Extract ALL decisions and ALL action items — miss nothing.
- Use professional, enterprise-grade language throughout.
- If something is not mentioned, write "Not specified" — NEVER invent data.
- The Action Items table columns must be: # | Task | Owner | Deadline | Status
- Always include the Notification Preview section.`;

function extractParticipants(report: string): string[] {
  const match = report.match(/\*\*Participants:\*\*\s*(.+)/);
  if (!match) return [];
  return match[1].split(",").map((p) => p.trim().split("(")[0].trim()).filter(Boolean);
}

function extractDecisions(report: string): string[] {
  const decisions: string[] = [];
  const section = report.match(/## Key Decisions\n([\s\S]*?)(?=\n---|\n##)/);
  if (!section) return decisions;
  const lines = section[1].split("\n").filter((l) => l.match(/^\d+\./));
  lines.forEach((l) => decisions.push(l.replace(/^\d+\.\s*/, "").trim()));
  return decisions;
}

function extractTitle(report: string): string {
  const match = report.match(/# Meeting Report — (.+)/);
  return match ? match[1].trim() : "Meeting";
}

export async function POST(req: NextRequest) {
  try {
    const { transcript, apiKey } = await req.json();

    if (!transcript || transcript.trim().length < 10) {
      return NextResponse.json({ error: "Transcript is too short or empty." }, { status: 400 });
    }

    const key = apiKey || process.env.OPENAI_API_KEY;
    if (!key) {
      return NextResponse.json({ error: "No OpenAI API key provided." }, { status: 400 });
    }

    const openai = new OpenAI({ apiKey: key });

    const completion = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: `Here is the meeting transcript/notes:\n\n${transcript}` },
      ],
      temperature: 0.3,
      max_tokens: 2500,
    });

    const report = completion.choices[0]?.message?.content ?? "";

    // Fire-and-forget: store in knowledge base, update analytics, create task reminders
    const baseUrl = req.nextUrl.origin;
    const title = extractTitle(report);
    const participants = extractParticipants(report);
    const decisions = extractDecisions(report);

    // Count action items from the table
    const actionItemRows = [...report.matchAll(/\|\s*\d+\s*\|(.+?)\|(.+?)\|(.+?)\|/g)];
    const actionItems = actionItemRows
      .map((m) => ({
        task: m[1].trim(),
        owner: m[2].trim(),
        deadline: m[3].trim(),
      }))
      .filter((a) => a.task && a.owner && a.owner !== "Owner" && a.task !== "Task");

    // Store in knowledge base
    fetch(`${baseUrl}/api/knowledge-base`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        action: "store",
        meetingData: { title, participants, report, decisions, actionItems },
      }),
    }).catch(() => {});

    // Update analytics
    fetch(`${baseUrl}/api/analytics`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        action: "update",
        updateData: { meetingCount: 1, taskCount: actionItems.length },
      }),
    }).catch(() => {});

    // Create task reminders for each action item
    actionItems.forEach((item) => {
      const firstName = item.owner.split(" ")[0];
      fetch(`${baseUrl}/api/task-reminders`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action: "create",
          owner: item.owner,
          email: `${firstName.toLowerCase()}@company.com`,
          task: item.task,
          deadline: item.deadline,
        }),
      }).catch(() => {});
    });

    return NextResponse.json({ report, actionItemsCount: actionItems.length, participants });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
